# embed_binary(<input> <symbol> <output.cpp>)
# Generates a C++ source defining `extern const unsigned char <symbol>[]` and
# `extern const std::size_t <symbol>Size` with the bytes of <input>, at
# configure time (re-run automatically when <input> changes).
function(embed_binary input symbol output)
    file(READ "${input}" hex HEX)
    # 16 bytes per line, then 0xNN, per byte (CMake regexes have no {n}).
    string(REPEAT "[0-9a-f][0-9a-f]" 16 line_re)
    string(REGEX REPLACE "(${line_re})" "\\1\n" hex "${hex}")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    file(WRITE "${output}.tmp"
        "// Generated by cmake/embed.cmake from ${input}. Do not edit.\n"
        "#include <cstddef>\n"
        "extern const unsigned char ${symbol}[];\n"
        "extern const std::size_t ${symbol}Size;\n"
        "const unsigned char ${symbol}[] = {\n${bytes}\n};\n"
        "const std::size_t ${symbol}Size = sizeof(${symbol});\n")
    file(COPY_FILE "${output}.tmp" "${output}" ONLY_IF_DIFFERENT)
    file(REMOVE "${output}.tmp")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${input}")
endfunction()
